import { Container, Row, Col } from 'reactstrap'
import Navbar from '../components/Header/BarNav'
import Button from '../components/Hero/Button'
import TitleSection from '../components/common/titleSection'
import Img from '../components/Header/image'
import ImgHero from '../components/Hero/image'
import ClientsBar from '../components/clients/clientsBar'
import CarouselFadeExample from '../components/Hero/Caroseul'
import CardHero from '../components/Hero/CardHero'
import Card from '../components/Hero/Card'
import EndHero from '../components/Hero/EndHero'
import  { DiCss3 } from "react-icons/di"
import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {

  const clients = [
    {
      id: "1",
      image: "https://w7.pngwing.com/pngs/732/34/png-transparent-logo-amazon-com-brand-flipkart-others-text-orange-logo-thumbnail.png"
    },
    {
      id: "2",
      image: "https://w7.pngwing.com/pngs/715/121/png-transparent-logo-sparco-brand-font-product-brand-distro-text-logo-brand-thumbnail.png"
    },
    {
      id: "3",
      image: "https://1000logos.net/wp-content/uploads/2020/09/Oreo-logo.jpg"
    },
    {
      id: "4",
      image: "https://w7.pngwing.com/pngs/280/326/png-transparent-logo-netflix-logos-and-brands-icon-thumbnail.png"
    },
    {
      id: "5",
      image: "https://w7.pngwing.com/pngs/147/564/png-transparent-puma-logo-brand-adidas-sneakers-adidas-cat-like-mammal-carnivoran-hand-thumbnail.png"
    },
    {
      id: "6",
      image: "https://png.pngitem.com/pimgs/s/492-4927353_under-armour-logo-png-under-armour-brand-logo.png"
    },
    {
      id: "7",
      image: "https://png.pngitem.com/pimgs/s/492-4927353_under-armour-logo-png-under-armour-brand-logo.png"
    },
  ]


  return (
    <>
      <Head>
        <title>LandingPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        title={'Ciao'}
      />
      <Container>
        <Row className={styles.flexcontainer}>
          <Col md="8" className={styles.textheader}>
            <h1><strong>Al-Powered Brand Tracking</strong></h1>
            <p>We help brands make better marketing decisions by
              delivering world-class, scalable insights.</p>
            <Button title={'Book Demo'} />
          </Col>
          <Col md="4">
            <Img src={"https://www.upmagazinearezzo.it/atladv/wp-content/uploads/2021/01/img-01.png"} />
          </Col>
        </Row>
        <p className={styles.p}>Trusted by some of the world's most innovative brands</p> 
        <Row className={styles.flexcontainer}> 
          {clients.map((client) => {
            return (
              <ClientsBar
                key={client.id}
                client={client}
              />
            )
          })}
        </Row>
        <div className={styles.flexcontainer}>
          <div className={styles.containerImage}>
            <ImgHero src="https://mobile-marketing.it/wp-content/uploads/2022/12/Social-Media-Comparison-Chart-Infographic-Graph-13.png"/>
          </div>
          <div className={styles.containerCard}>
            <CardHero 
              title={'Brand Awareness'}
              content={'Measure the effectiveness of your marketing strategy by understandingconsumer perception about your brand and how it changes over time. Choose from hundreds of standardized association metrics or create your own.'}
              href= {'#'}
              link={'Learn More'}
            />
          </div>
        </div>
        <TitleSection 
            title= "Smarter Tools. Better Marketing Decisions."
          />
        <Row className={styles.flexcontainer}>
          <Col md="4">
            <Card 
              icon={() => <DiCss3 />}
              title={'Castomizable Dashboard'}
              content={'Measure only what you need. Our intuitive dashboard can be customized to track the KPIs most important for you'}
            />
          </Col>
          <Col md="4">
            <Card
              icon={() => <DiCss3 />}
              title={'Reliable Data'}
              content={'Get high-quality insights generated throught machine learning algorithms to ensure unprecedented occuracy and granularity'}
            />
          </Col>
          <Col md="4">
            <Card
              icon={() => <DiCss3 />}
              title={'Deep Segmentation'}
              content={'Choose from over 1000+ profile attributes to build the target audiences that matter most for your brand.'}
            />
          </Col>
        </Row>
        <Row>
          <Col md="12"></Col>
        </Row>
        <TitleSection 
            title= "Access the Pulse of Human Perception"
          />
        <Row className={styles.row}>
          <Col>
            <ImgHero 
              type= "large"
              src="https://www.mlaworld.com/wp-content/uploads/2015/08/ragazza-che-ascolta-musica.jpg"
            />
          </Col>
        </Row>
        <TitleSection 
            title= "Hear From Our Customers"
          />
        <Row className={styles.flexcontainer}> 
          {clients.map((client) => {
            return (
              <ClientsBar
                key={client.id}
                client={client}
              />
            )
          })}
        </Row>
        <Row className={styles.flexcontainer}>
          <Col md="2">
            <ImgHero 
              type= "small"
              src="https://www.rivaliq.com/wp-content/uploads/2015/01/engineering-and-marketing.jpg"/>
          </Col>
          <Col>
            <CarouselFadeExample />
          </Col>
        </Row>
          <TitleSection 
            title= "Dive Into the World of Brand Tracking"
          />
          <Row className={styles.flexcontainer}>
          <Col md="4">
            <Card 
              icon={() => <DiCss3 />}
              title={'Castomizable Dashboard'}
              content={'Measure only what you need. Our intuitive dashboard can be customized to track the KPIs most important for you'}
              buttonTitle={'Beauty'}
              type={'beauty'}
            />
          </Col>
          <Col md="4">
            <Card
              icon={() => <DiCss3 />}
              title={'Reliable Data'}
              content={'Get high-quality insights generated throught machine learning algorithms to ensure unprecedented occuracy and granularity'}
              buttonTitle={'Entertaiment'}
              type= {'entertaiment'}
            />
          </Col>
          <Col md="4">
            <Card
              icon={() => <DiCss3 />}
              title={'Deep Segmentation'}
              content={'Choose from over 1000+ profile attributes to build the target audiences that matter most for your brand.'}
              buttonTitle={'Apparel'}
              type= {'apparel'}
            />
          </Col>
        </Row>
        <Row className={styles.row}>
          <Button title={'Learn More'} />
        </Row>
        <Row>
          <EndHero 
            title={'Make your first step the right one'}
            content={'Learn how you can use Latana to improve your brand marketing and grow faster'}
            buttonTitle={'Book Demo'}
          />
        </Row>
        <Row>

        </Row>
      </Container>

    </>
  )
}
