import dynamic from 'next/dynamic'
import Button from '../components/Hero/Button'
import TitleSection from '../components/common/TitleSection'
import ImgHeader from '../components/Header/ImageHeader'
import ImgHero from '../components/Hero/ImageHero'
import ClientsBar from '../components/clients/clientsBar'
import DemoCarousel from '../components/Hero/DemoCarousel'
import CardHero from '../components/Hero/CardHero'
import Card from '../components/Hero/Card'
import CarouselBrand from '../components/Hero/CarouselBrand'
import EndHero from '../components/Hero/EndHero'
import { DiCss3 } from "react-icons/di"
import Head from 'next/head'
import Footer from '../components/footer/Footer'
import NewsLetter from '../components/footer/NewsLetter'
import Privacy from '../components/footer/PrivacyCopyr'
import styles from '../styles/Home.module.css'

const CardDynamic = dynamic(
  () => import('../components/Hero/CardDynamic'),
  { ssr: false }
)

const Navbar = dynamic(
  () => import('../components/Header/NavBar'),
  { ssr: false }
)

export default function Home() {

  const clients = [
    {
      id: "1",
      image: "https://w7.pngwing.com/pngs/732/34/png-transparent-logo-amazon-com-brand-flipkart-others-text-orange-logo-thumbnail.png"
    },
    {
      id: "2",
      image: "https://w7.pngwing.com/pngs/715/121/png-transparent-logo-sparco-brand-font-product-brand-distro-text-logo-brand-thumbnail.png"
    },
    {
      id: "3",
      image: "https://1000logos.net/wp-content/uploads/2020/09/Oreo-logo.jpg"
    },
    {
      id: "4",
      image: "https://w7.pngwing.com/pngs/280/326/png-transparent-logo-netflix-logos-and-brands-icon-thumbnail.png"
    },
    {
      id: "5",
      image: "https://w7.pngwing.com/pngs/147/564/png-transparent-puma-logo-brand-adidas-sneakers-adidas-cat-like-mammal-carnivoran-hand-thumbnail.png"
    },
    {
      id: "6",
      image: "https://png.pngitem.com/pimgs/s/492-4927353_under-armour-logo-png-under-armour-brand-logo.png"
    },
    {
      id: "7",
      image: "https://png.pngitem.com/pimgs/s/492-4927353_under-armour-logo-png-under-armour-brand-logo.png"
    },
  ]


  return (
    <>
      <Head>
        <title>LandingPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>
        <div className={styles.flexContainer}>
          <div className={styles.textHeader}>
            <h1 className={styles.h1} ><strong>Al-Powered Brand Tracking</strong></h1>
            <p className={styles.p}>We help brands make better marketing decisions by
              delivering world-class, scalable insights.</p>
            <Button title={'Book Demo'} />
          </div>
          <div className={styles.col}>
            <ImgHeader src={"https://www.upmagazinearezzo.it/atladv/wp-content/uploads/2021/01/img-01.png"} />
          </div>
        </div>
        <p className={styles.p}>Trusted by some of the world's most innovative brands</p>
        <div className={styles.containerClients}>
          {clients.map((client) => {
            return (
              <ClientsBar
                key={client.id}
                client={client}
              />
            )
          })}
        </div>
        <div className={styles.flexContainer}>
          <div className={styles.containerImage}>
            <ImgHero src="https://mobile-marketing.it/wp-content/uploads/2022/12/Social-Media-Comparison-Chart-Infographic-Graph-13.png" />
          </div>
          <div className={styles.containerCard}>
            <CardHero
              title={'Brand Awareness'}
              content={'Measure the effectiveness of your marketing strategy by understandingconsumer perception about your brand and how it changes over time. Choose from hundreds of standardized association metrics or create your own.'}
              href={'#'}
              textLink={'Learn More'}
            />
            <div>
              <ul>
                <li className={styles.li}>Audience Segmentation</li>
                <li className={styles.li}>Research Expertis</li>
                <li className={styles.li}>Global Tracking</li>
              </ul>
            </div>
          </div>
        </div>
        <TitleSection
          title="Smarter Tools. Better Marketing Decisions."
        />
        <div className={styles.flexContainer}>
          <div className=''>
            <Card
              icon={() => <DiCss3 />}
              title={'Castomizable Dashboard'}
              content={'Measure only what you need. Our intuitive dashboard can be customized to track the KPIs most important for you'}
            />
          </div>
          <div className=''>
            <Card
              icon={() => <DiCss3 />}
              title={'Reliable Data'}
              content={'Get high-quality insights generated throught machine learning algorithms to ensure unprecedented occuracy and granularity'}
            />
          </div>
          <div className=''>
            <Card
              icon={() => <DiCss3 />}
              title={'Deep Segmentation'}
              content={'Choose from over 1000+ profile attributes to build the target audiences that matter most for your brand.'}
            />
          </div>
        </div>
        <TitleSection
          title="Access the Pulse of Human Perception"
        />
        <div className={styles.row}>
          <div className=''>
            <ImgHero
              type="small"
              src="https://www.mlaworld.com/wp-content/uploads/2015/08/ragazza-che-ascolta-musica.jpg"
            />
          </div>
        </div>
        <TitleSection
          title="Hear From Our Customers"
        />
        <div className={styles.centerCarouselBrand}>
          <CarouselBrand />
        </div>
        <div className={styles.flexContainer}>
          <div className={styles.col}>
            <ImgHero
              type="small"
              src="https://www.rivaliq.com/wp-content/uploads/2015/01/engineering-and-marketing.jpg" />
          </div>
          <div className='col-md-10' style={{ margin: 'auto' }}>
            <DemoCarousel />
          </div>
        </div>
        <TitleSection
          title="Dive Into the World of Brand Tracking"
        />
        <div className={styles.centerCarousel}>
          <CardDynamic />
        </div>
        <div className={styles.row}>
          <Button title={'Learn More'} />
        </div>
        <div className='row'>
          <EndHero
            title={'Make your first step the right one'}
            content={'Learn how you can use Latana to improve your brand marketing and grow faster'}
            buttonTitle={'Book Demo'}
          />
        </div>
        <Footer />
        <NewsLetter />
        <Privacy />
      </div>
    </>
  )
}
